[package]
name = "libtwitch-rs"
version = "0.1.1"
edition = "2018"
authors = ["the libtwitch-rs authors"]
description = "Rust library for the Twitch API"
repository = "https://github.com/simonsan/libtwitch-rs"
readme = "README.md"
keywords = ["twitch", "api"]
categories = ["api-bindings"]
license = "AGPL-3.0"

[dependencies]
chrono = { version = "0.3", features = ["serde", "rustc-serialize"] }
hyper = "0.10.4"
hyper-rustls = "0.6.0"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
toml = "0.3.2"
urlparse = "0.7.3"

[dev-dependencies]
lazy_static = "1.4.0"
pretty_assertions = "0.4.0"